metaxtract_exe: "bin/MetaXtract.v.0.5.1.exe"

pride:
  url: "ftp://ftp.pride.ebi.ac.uk/pride/data/archive"
  year: 2025
  month: 1           # 1â€“12
  max_files: 2                # 0 = all .raw, N = newest N .raw
  copy_dir: "results/data"    # local cache for RAWs before analysis

output_dir: "results"
metaxtract_config: "metaxtract_config.yaml"

options:
  file_based_details: true          # --file-based-details
  ms_method: true                   # --ms-method
  lc_method: true                   # --lc-method
  graphical_representation: false   # --graphical-representation
  complete_ms2: false                # --complete-ms2
  complete_ms1: false               # --complete-ms1
